### ISSUE TITLE
Applications from side bar menu not popping up on first time load of web app

### ISSUE THREAD

**Issue by shivaylamba** [raghavdhingra/Web-OS#2]
https://user-images.githubusercontent.com/19529592/122641429-fab21480-d122-11eb-8af7-9db26745502d.mp4

**Comment by shivaylamba** [comment]
@raghavdhingra please take a look. The applications from side bar menu don't pop up despite being stored in the activities array. They only appear after one of the application is selected from the main home screen.

**Comment by raghavdhingra** [comment]
Thanks, @shivaylamba for pointing the issue! Fixing that.
